services:
  aca-py:
    image: ghcr.io/openwallet-foundation/acapy-agent:py3.12-1.2.2
    environment:
      - ACAPY_AUTO_ACCEPT_INVITES=true
      - ACAPY_AUTO_ACCEPT_REQUESTS=true
      - ACAPY_AUTO_PROMOTE_AUTHOR_DID=true
      - ACAPY_AUTO_PROVISION=true
      - ACAPY_AUTO_REQUEST_ENDORSEMENT=true
      - ACAPY_AUTO_VERIFY_PRESENTATION=true
      - ACAPY_AUTO_WRITE_TRANSACTIONS=true
      - ACAPY_CREATE_REVOCATION_TRANSACTIONS=true
      - ACAPY_ENDORSER_ALIAS=endorser
      - ACAPY_ENDORSER_PUBLIC_DID=${ACAPY_ENDORSER_PUBLIC_DID}
      - ACAPY_ENDORSER_ROLE=author
      - ACAPY_ENDPOINT=${AGENT_ENDPOINT}
      - ACAPY_GENESIS_TRANSACTIONS_LIST=/tmp/ledgers.yaml
      - ACAPY_LABEL=${AGENT_NAME}
      - ACAPY_LOG_LEVEL=info
      - ACAPY_READ_ONLY_LEDGER=false
      - ACAPY_TAILS_SERVER_BASE_URL=https://tails-dev.vonx.io
      - ACAPY_TAILS_SERVER_UPLOAD_URL=https://tails-dev.vonx.io
      - ACAPY_WALLET_KEY=${WALLET_ENCRYPTION_KEY}
      - ACAPY_WALLET_NAME=single_tenant_wallet
      - ACAPY_WALLET_STORAGE_TYPE=${WALLET_TYPE}
      - ACAPY_WALLET_TYPE=askar
      - AGENT_ADMIN_API_KEY=change-me
      - POSTGRESQL_WALLET_HOST=${POSTGRESQL_WALLET_HOST}
      - POSTGRESQL_WALLET_PASSWORD=${POSTGRESQL_WALLET_PASSWORD}
      - POSTGRESQL_WALLET_PORT=${POSTGRESQL_WALLET_PORT}
      - POSTGRESQL_WALLET_USER=${POSTGRESQL_WALLET_USER}
      # - ACAPY_ENDORSER_PUBLIC_DID=${ACAPY_ENDORSER_PUBLIC_DID}
      # - ACAPY_WALLET_LOCAL_DID=true
      # - ACAPY_WALLET_SEED=${AGENT_WALLET_SEED}
      # - ACAPY_WEBHOOK_URL=${CONTROLLER_WEB_HOOK_URL}
    ports:
      - ${AGENT_ADMIN_PORT}:${AGENT_ADMIN_PORT}
      - ${AGENT_HTTP_PORT}:${AGENT_HTTP_PORT}
    networks:
      - single_tenant_network
    volumes:
      - ./agent/config/ledgers.yaml:/tmp/ledgers.yaml
    depends_on:
      - wallet-db
    entrypoint: /bin/bash
    command:
      [
        "-c",
        'sleep 15; aca-py start --inbound-transport http ''0.0.0.0'' ${AGENT_HTTP_PORT} --outbound-transport http --wallet-storage-config ''{"url":"${POSTGRESQL_WALLET_HOST}:${POSTGRESQL_WALLET_PORT}","max_connections":5}'' --wallet-storage-creds ''{"account":"${POSTGRESQL_WALLET_USER}","password":"${POSTGRESQL_WALLET_PASSWORD}","admin_account":"${POSTGRESQL_WALLET_USER}","admin_password":"${POSTGRESQL_WALLET_PASSWORD}"}'' --admin ''0.0.0.0'' ${AGENT_ADMIN_PORT} --${AGENT_ADMIN_MODE} ',
      ]

  wallet-db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRESQL_WALLET_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_WALLET_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_WALLET_DATABASE}
    networks:
      - single_tenant_network
    ports:
      - 5433:5432
    volumes:
      - agent-wallet-db:/var/lib/pgsql/data

networks:
  single_tenant_network:
    driver: bridge

volumes:
  agent-wallet-db:
